/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Lab1_demo;

public class Library {
    public static void main(String arg[]) {
    	Library lib = new Library();
    	if(lib.someLibraryMethod())
    		System.out.println("demo");
    }
    public boolean someLibraryMethod() {
        return true;
    }
}
